version: 2.0

jobs:
  unit-tests:
    working_directory: /go/src/s32x.com/ipdata
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: go test ./...
  dockerhub:
    working_directory: /go/src/s32x.com/ipdata
    environment:
      - DOCKER_TAG: s32x/ipdata
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build --no-cache -t $DOCKER_TAG .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push $DOCKER_TAG
  deploy:
    working_directory: /go/src/s32x.com/ipdata
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: curl -sf https://up.apex.sh/install | BINDIR=. sh
      - run: ./up upgrade
      - run: ./up deploy production
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - unit-tests
      - dockerhub:
          requires:
            - unit-tests
      - deploy:
          requires:
            - unit-tests